name: CICD

on: 
 push:
   branches: ["main"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "hello"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: testing code
        run: echo "Teting code"
  deploy:
     runs-on: ubuntu-latest
     steps:
       - name: deploying the code
         run: echo "Deploying the code"
