name: Hello

on: 
 push: 
 workflow_dispatch:
   inputs:
     environments:
      description: 
      required: true
      type: choice
      options:
        - dev
        - prod
        - staging
     

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: say hello to users
        run: echo "Hello users"

      - name: user will test this environment
        run: echo "run this test"
